### ISSUE TITLE
People picker selection mode single still selects multiple users

### ISSUE THREAD

**Issue by Jcardif** [CommunityToolkit/Graph-Controls#65]
## Selection Mode not working as expected
I have set the picker on xaml as follows:
```xaml
                    <controls:PeoplePicker
                        PlaceholderText="Select Engineer on Duty*"
                        RelativePanel.Below="RootCauseTextBox"
                        Margin="{StaticResource MediumTopMargin}"
                        Width="200" Height="35"
                        Padding="{StaticResource MediumTopMargin}"
                        SelectionMode="Single" 
                        Name="FieldEngineerPicker"/>
```
However, it allows for multiple selection of people when I run it. 

## Expected behavior
Only one user should be selected from the dropdown list

## Environment

```
Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] Insider Build (build number:20279.fe_release.201209-1322 )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [x] 2019 (version: 16.8) 
- [ ] 2019 Preview (version: )

```

**Comment by michael-hawker** [comment]
Thanks for the bug report @Jcardif, this is an underlying issue with the base `TokenizingTextBox` control. 

The TokenizingTextBox was built inherently with multiple selection in it's core purpose, otherwise a drop-down using the `PersonView` within the template is a better UX choice? Could you describe your user scenario in a bit more detail? Maybe we need a different version of this control somewhere to help encapsulate that better?

The `SelectionMode` property is just coming from `ListViewBase` and we never intended to hook it up into this control, though I'm not sure if we can hide it... I've filed a bug in our main repo for tracking that discussion there: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3672

**Comment by Jcardif** [comment]
my application is used to select a user from Graph and assign a specific app role and the requirements are that only one user **should** be assigned at a time, the current picker selects multiple users unfortunately. Or is there another control for this purpose?

**Comment by michael-hawker** [comment]
@Jcardif we don't have a control that provides that functionality out of the box. We only have the multi-select scenario setup through TokenizingTextBox. You can look [at the source](https://github.com/windows-toolkit/Graph-Controls/blob/main/Microsoft.Toolkit.Graph/Extensions/GraphExtensions.cs#L57-L98) we have here to get the call you need from the Graph and just use that to populate a normal `ComboBox` control.

**Comment by shweaver-MSFT** [comment]
Support for restricting the TokenizingTextBox is in PR in the WCT repo currently: https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4163

Once that gets figured out, the PeoplePicker control can then take advantage of that feature to resolve/support this scenario! :ship:

**Comment by shweaver-MSFT** [comment]
The feature has been added to the TokenizingTextBox in Windows Community Toolkit 🚀 The PeoplePicker will have the new `MaximumTokens` property for limiting the number of allowable tokens in the upcoming 7.1.0 release.
