### ISSUE TITLE
7.0.0 Release Plan

### ISSUE THREAD

**Issue by shweaver-MSFT** [CommunityToolkit/Graph-Controls#81]
# 7.0.0 Release Plan

This plan captures our work for the initial release of our authentication providers and Graph helpers. 

We plan to focus first on enabling authentication for NetStandard 2.0 apps via MSAL or directly through native Windows dialogues. This will allow our community to start building more experiences on top of the authentication providers right away. Our other helpers and controls will continue to stay in preview for now. We will be working hard to bring a follow-up release with the controls and helpers ready for production use in the near future.

https://github.com/windows-toolkit/Graph-Controls/milestone/1

## The plan

The Windows Community Toolkit Graph-Controls repo will have it's first release focused primarily on enabling authentication and Graph client access. We will ship as an additional set of packages of the 7.0 release of WCT. The packages are as follows:

### CommunityToolkit.Authentication
The authentication package includes basic structures for supporting a global authentication provider and responding to provider state change events.

### CommunityToolkit.Authentication.Msal
Enables authentication via the official Microsoft Authentication Library (MSAL).

### CommunityToolkit.Authentication.Uwp
Enables authentication through native WAM APIs.

### CommunityToolkit.Graph
Enables access to a pre-configured GraphServiceClient, used for making ad-hoc Graph API calls using the Graph SDK for the currently signed-in user.

Legend of annotations:

| Symbol | Description |
| ------ | ----------- |
| :zero: | priority 0 - must have for this release |
| :one:  | priority 1 - nice to have for this release |
| :two:  | priority 2 - stretch goal - unlikely for this release but we will try our best |
| :exclamation: | missing issue reference |
| :flashlight:  | investigating |

### Authentication

Developers can leverage the toolkit for authentication:

- [x] :zero: in NetStandard apps - #60
- [x] :zero: without requiring the Graph SDK - #75
- [x] :zero: using native Windows dialogues - #83
- [x] :zero: using the MSAL library - #78
- [x] :zero: with the V1 or beta endpoint independently - #52
- [x] :zero::exclamation: with clear documentation - [PR](https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/pull/533)
- [x] :one::exclamation: with clear samples of how to authenticate in WPF and UWP
- [x] :one::exclamation: with clear samples of how to make Graph requests in WPF and UWP
- [x] :one: WindowsProvider supports organizational accounts from AAD - #116

# Looking forward

Our initial 7.0.0 release is mostly focused on making the authentication providers available so developers can authenticate easily and make their own calls to the Graph with a pre-configured client. But we know there is so much more we can do on top to enable developers to do more with Microsoft Graph in their applications.

We plan to quickly follow up with a 7.1.0 release, including AAD support in WindowsProvider, helpers for roaming data between apps using Graph, as well as a variety of templated controls for UWP.

**Comment by shweaver-MSFT** [comment]
Update, we are rolling the plan for 7.0.0 into our plan for 7.1.0 and doing a preview release alongside Windows Community Toolkit 👍 

See the updated plan here -> [7.1.0 Release Plan](https://github.com/CommunityToolkit/Graph-Controls/issues/104)
